We applet profiles and page routing refactor
lightningrodlabs/acorn pull request #208
Opened 2022-11-02 16:26 UTC by weswalla

2022-11-04 23:05 UTC, weswalla commented
We are currently pausing this PR until React has been updated to 17/18. The reason being is that events inside react components were not registering within the shadow DOM. According to https://github.com/facebook/react/issues/10422 this is not an issue with React 17+

2022-11-05 03:37 UTC, weswalla commented
with the successful bump of the react version and events working inside the shadow DOM, it seems that the remaining big issues are to do with CSS and imported assets (fonts, images, etc)

2022-11-07 17:26 UTC, Connoropolous commented
ok great. as we've seen some of the CSS operational, it seems clear we can fix it. 
Re. the imported assets, I am more confident about images than fonts. 
We should be able to instruct webpack to deliver the image assets as base64 encoded strings, inline, instead of being an image asset served at an endpoint.

2022-11-07 17:52 UTC, Connoropolous requested changes
it looks like for CSS this may be your issue: 

" It creates a CSS file per JS file which contains CSS. " https://webpack.js.org/plugins/mini-css-extract-plugin/

filename:

<img width="775" alt="Screenshot 2022-11-07 at 9 49 56 AM" src="https://user-images.githubusercontent.com/1409121/200379832-2d87d296-29d9-4af2-9fe7-b20cf985e109.png">

There may only be the contents of one css file in your output file. I don't have the perfect solution off the top of my head but that's my diagnosis at the moment

2022-11-07 17:56 UTC, Connoropolous commented
> ok great. as we've seen some of the CSS operational, it seems clear we can fix it. Re. the imported assets, I am more confident about images than fonts. We should be able to instruct webpack to deliver the image assets as base64 encoded strings, inline, instead of being an image asset served at an endpoint.

I believe that "inlining assets" is essentially the path
https://webpack.js.org/guides/asset-modules/#inlining-assets

2022-11-07 18:00 UTC, Connoropolous commented
<img width="683" alt="Screenshot 2022-11-07 at 9 58 10 AM" src="https://user-images.githubusercontent.com/1409121/200381604-9f3ec2c9-4fab-4ece-aa5b-382de2796268.png">

I mentioned base64 encoded strings, and this is the same thing: "data URI"
(see https://en.wikipedia.org/wiki/Data_URI_scheme)

2022-11-14 18:55 UTC, Connoropolous commented on web/src/routes/ProjectView/MapView/selector.ts
> +  }, // state.projects.projectMeta[activeProject],
this will require a proper solution that works across both Acorn runtime contexts

2022-11-15 01:43 UTC, weswalla reviewed
the project meta info should only be created on applet install

2022-12-27 18:41 UTC, Connoropolous commented
maybe condense the two PRs down into just one at this point? 
You can edit the "base" branch so that it gives a comparison against `main`

2025-04-15 03:40 UTC, closed without merging